<?php

namespace Database\Seeders;

use App\Models\ActivePharmaceuticalIngredient;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ApiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $apis = [
            [
                'name' => 'ALUMINIUM HYDROXIDE GEL',
                'description' => 'A pharmaceutical-grade aluminum hydroxide gel, commonly used as an antacid.',
                'manufacturer' => 'VASUNDHARA',
                'country' => 'India',
                'packaging' => 'Bag',
                'packing_size' => '20 KG',
            ],
            [
                'name' => 'ALFA CALCIDOL',
                'description' => 'A synthetic vitamin D analog used in the treatment of calcium metabolism disorders.',
                'manufacturer' => 'CENTURY',
                'country' => 'India',
                'packaging' => 'Drum',
                'packing_size' => '300 MG',
            ],
            [
                'name' => 'ALFA LIPOIC ACID',
                'description' => 'A potent antioxidant compound used in dietary supplements and pharmaceuticals.',
                'manufacturer' => 'TOYO HAKKO/FUSHILAI',
                'country' => 'Japan',
                'packaging' => 'Carton',
                'packing_size' => '20 KG',
            ],
            [
                'name' => 'ATORVASTATIN',
                'description' => 'An active pharmaceutical ingredient (API) used in medication to lower cholesterol.',
                'manufacturer' => 'MOREPEN',
                'country' => 'India',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'CALCIUM POLYSTERENE',
                'description' => 'A resin used in medication to treat high levels of potassium in the blood.',
                'manufacturer' => 'ION EXCHANGE',
                'country' => 'India',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'CELECOXIB',
                'description' => 'A nonsteroidal anti-inflammatory drug (NSAID) used for treating pain and inflammation.',
                'manufacturer' => 'HETERO',
                'country' => 'India',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'CALCITRIOL',
                'description' => 'The active form of vitamin D, used to treat and prevent low calcium levels.',
                'manufacturer' => 'CARBOGEN',
                'country' => 'Europe',
                'packaging' => 'Drum',
                'packing_size' => '25 MG',
            ],
            [
                'name' => 'CITICOLINE SODIUM',
                'description' => 'A nootropic compound used in supplements to support cognitive function and brain health.',
                'manufacturer' => 'XINXIANG/SUZHOU TIANMA',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'COLEUS ATROPURPUREUS EXTRACT',
                'description' => 'A herbal extract from the Coleus plant, often used for various health benefits.',
                'manufacturer' => 'NATURALIN',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'EXTRACT BROMELAIN',
                'description' => 'An enzyme extract from pineapple, used as a digestive aid and anti-inflammatory supplement.',
                'manufacturer' => 'WISAPPLE/ORGANIC',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'EPIMEDIUM',
                'description' => 'A herbal extract, also known as Horny Goat Weed, used in traditional medicine.',
                'manufacturer' => 'ORGANIC',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'ETORICOXIB',
                'description' => 'A selective COX-2 inhibitor (NSAID) used for the relief of pain and inflammation.',
                'manufacturer' => 'HONOUR',
                'country' => 'India',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'ENTECAVIR',
                'description' => 'An antiviral medication used in the treatment of hepatitis B virus (HBV) infection.',
                'manufacturer' => 'HETERO',
                'country' => 'India',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'EPA/DHA OIL',
                'description' => 'A concentrated oil containing essential Omega-3 fatty acids, eicosapentaenoic acid and docosahexaenoic acid.',
                'manufacturer' => 'HUATHAI BIOPHARM',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'FEXOFENADINE',
                'description' => 'An antihistamine drug used in the treatment of allergy symptoms.',
                'manufacturer' => 'MOREPEN',
                'country' => 'India',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'GENESTEIN',
                'description' => 'An isoflavone found in soy products, studied for its potential health benefits.',
                'manufacturer' => 'SHANGHAI PASSIONO',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'GINSENG',
                'description' => 'A popular herbal extract from the root of the ginseng plant, used as a health supplement.',
                'manufacturer' => 'ORGANIC',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'HOODIA GORDONII EXTRACT',
                'description' => 'A plant extract traditionally used as an appetite suppressant.',
                'manufacturer' => 'NUTRA GREEN',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25KG',
            ],
            [
                'name' => 'HYDROTYROSOL (OLIVE EXTRACT)',
                'description' => 'A powerful antioxidant polyphenol extracted from olives and olive leaves.',
                'manufacturer' => 'HUISONG',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'KAEMPFERIA AGUSTIFOLIA',
                'description' => 'A herbal extract from a species of the ginger family, used in traditional remedies.',
                'manufacturer' => 'ORGANIC',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'KETOROLAC TROMETHAMINE',
                'description' => 'A nonsteroidal anti-inflammatory drug (NSAID) for short-term management of moderate to severe pain.',
                'manufacturer' => 'VASUDHA',
                'country' => 'India',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'KETOCONAZOLE',
                'description' => 'An antifungal medication used to treat a number of fungal infections.',
                'manufacturer' => 'AARTI',
                'country' => 'India',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'KETOPROFEN MICRONIZED',
                'description' => 'A micronized form of an NSAID used to relieve pain and inflammation.',
                'manufacturer' => 'HUBEI XUNDA PHARM',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'KRILL OIL',
                'description' => 'An oil derived from krill, rich in omega-3 fatty acids EPA and DHA.',
                'manufacturer' => 'LUHUA BIOMARINE',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'L CARNITINE FUMARATE',
                'description' => 'A stable form of L-Carnitine, an amino acid derivative involved in metabolism.',
                'manufacturer' => 'KAIYUAN HENGTHAI',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'L CYSTEINE',
                'description' => 'A semi-essential amino acid used in pharmaceuticals and food production.',
                'manufacturer' => 'SHANGHAI PASSIONP',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'L CYSTINE',
                'description' => 'The oxidized dimer form of the amino acid cysteine, used in supplements.',
                'manufacturer' => 'SHANGHAI PASSIONO',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'LEVOCETIRIZINE DIHYDROCHLORIDE',
                'description' => 'An antihistamine used to relieve allergy symptoms such as watery eyes, runny nose, and sneezing.',
                'manufacturer' => 'GLOCHEM',
                'country' => 'India',
                'packaging' => 'Drum',
                'packing_size' => '5 KG',
            ],
            [
                'name' => 'LEVOFLOXACIN HEMIHYDRATE',
                'description' => 'A broad-spectrum fluoroquinolone antibiotic used to treat bacterial infections.',
                'manufacturer' => 'ZHEJIANG EAST',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'LICORICE EXTRACT',
                'description' => 'A natural extract from the root of the licorice plant, used for flavoring and herbal remedies.',
                'manufacturer' => 'XINJIANG ALAR',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'LINAGLIPTINE',
                'description' => 'An oral medication used to treat type 2 diabetes by increasing insulin levels.',
                'manufacturer' => 'HETERO',
                'country' => 'India',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'LINAGLIPTINE PREMIX',
                'description' => 'A premixed formulation containing Linagliptine for pharmaceutical manufacturing.',
                'manufacturer' => 'HETERO',
                'country' => 'India',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'METHYL SULFONYL METHANE',
                'description' => 'Also known as MSM, a popular dietary supplement used to support joint health.',
                'manufacturer' => 'YUEYANG XIANGMAO',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'MISOPROSTOL HPMC',
                'description' => 'A synthetic prostaglandin combined with HPMC, used for various medical purposes.',
                'manufacturer' => 'EVERLIGHT',
                'country' => 'Europe',
                'packaging' => 'Drum',
                'packing_size' => '1 KG',
            ],
            [
                'name' => 'MOLNUPIRAVIR',
                'description' => 'An oral antiviral medication used for the treatment of certain viral infections.',
                'manufacturer' => 'UNIVERSAL PHARMA',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'MADDER ROOT EXTRACT',
                'description' => 'A natural colorant and herbal extract derived from the root of the madder plant.',
                'manufacturer' => 'ORGANIC',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'MILK THISTLE/SILYBUM MARIANUM EXTRACT',
                'description' => 'A herbal extract from the milk thistle plant, widely used for liver support.',
                'manufacturer' => 'HUISONG',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'NEOMYCIN SULFATE',
                'description' => 'An aminoglycoside antibiotic used to prevent or treat bacterial skin infections.',
                'manufacturer' => 'SICHUAN LONG MARCH',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'NATTOKINASE',
                'description' => 'An enzyme extracted from natto, a traditional Japanese fermented soybean food, used for cardiovascular support.',
                'manufacturer' => 'CONTEK LIFE',
                'country' => 'Korea',
                'packaging' => 'Drum',
                'packing_size' => '20 KG',
            ],
            [
                'name' => 'PAPAIN EXTRACT',
                'description' => 'A proteolytic enzyme extracted from the raw fruit of the papaya plant.',
                'manufacturer' => 'ORGANIC',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'PROPYL GALLATE',
                'description' => 'An antioxidant ester used as a preservative to prevent oxidation in foods, oils, and cosmetics.',
                'manufacturer' => 'JIURUI BIOLOGY',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'QUERCETIN EXTRACT',
                'description' => 'A plant flavonoid and antioxidant found in many fruits and vegetables.',
                'manufacturer' => 'XIAMEN',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'RANITIDINE',
                'description' => 'A medication that decreases stomach acid production, used to treat ulcers and GERD.',
                'manufacturer' => 'SMS LIFESCIENCE',
                'country' => 'India',
                'packaging' => 'Drum',
                'packing_size' => '15 KG',
            ],
            [
                'name' => 'RIFAMPICIN',
                'description' => 'An antibiotic used to treat several types of serious bacterial infections.',
                'manufacturer' => 'LUOHE NANJIECCN',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'ROSUVASTATIN CALCIUM',
                'description' => 'A statin medication used to prevent cardiovascular disease and treat high cholesterol.',
                'manufacturer' => 'NANTONG CHANYOO',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'RUTINBIOFLAVONOID EXTRACT',
                'description' => 'An extract rich in Rutin, a citrus bioflavonoid known for its antioxidant properties.',
                'manufacturer' => 'ORGANIC',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'SAW PALMETTO EXTRACT',
                'description' => 'An extract from the fruit of the Serenoa repens tree, commonly used for prostate health.',
                'manufacturer' => 'NATURALIN',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'SCHISANDRAE EXTRACT',
                'description' => 'An adaptogenic herb extract from the Schisandra berry, used in traditional Chinese medicine.',
                'manufacturer' => 'HUISONG',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'SOPHORA JAPONICA EXTRACT',
                'description' => 'A plant extract rich in flavonoids such as rutin and quercetin.',
                'manufacturer' => 'ORGANIC',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'SITAGLIPTIN',
                'description' => 'An anti-diabetic medication used to treat type 2 diabetes.',
                'manufacturer' => 'HONOUR LAB',
                'country' => 'India',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'TRIBULUS TERESTRIS',
                'description' => 'A plant extract commonly used in supplements for vitality and virility.',
                'manufacturer' => 'ORGANIC',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'TENOFOVIR DISOPROXIL FUMARATE',
                'description' => 'An antiviral medication used to treat chronic hepatitis B and to manage HIV/AIDS.',
                'manufacturer' => 'ACEBRIGHT',
                'country' => 'China/India',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'TAMSULOSIN',
                'description' => 'A medication used to treat symptoms of an enlarged prostate (BPH).',
                'manufacturer' => 'RACHEM',
                'country' => 'India',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'TRIMETHAZIDINE',
                'description' => 'An anti-anginal medication used for treating symptoms of angina pectoris.',
                'manufacturer' => 'USV',
                'country' => 'India',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'UNDERNATURED COLLAGEN',
                'description' => 'A type of collagen supplement (often Type II) used to support joint health.',
                'manufacturer' => 'BEYOND',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'VITAMIN B1 HCL',
                'description' => 'Thiamine hydrochloride, a form of Vitamin B1, an essential nutrient for metabolism.',
                'manufacturer' => 'JIANGXI TIANXIN',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'VITAMIN B1 MONO',
                'description' => 'Thiamine mononitrate, a stable form of Vitamin B1 used in food fortification.',
                'manufacturer' => 'JIANGXI TIANXIN',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'VITAMIN B12',
                'description' => 'Cobalamin, an essential vitamin crucial for brain function and the formation of red blood cells.',
                'manufacturer' => 'HEBEI HUARONG',
                'country' => 'China',
                'packaging' => 'Tin',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'VITAMIN B2 96%',
                'description' => 'Riboflavin with 96% purity, a vitamin essential for growth and overall good health.',
                'manufacturer' => 'HUBEI GUANGJI',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'VITAMIN B6 HCL',
                'description' => 'Pyridoxine hydrochloride, a form of Vitamin B6 vital for numerous metabolic reactions.',
                'manufacturer' => 'JIANGXI TIANXIN',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'WHITE WILLOW BARK',
                'description' => 'A herbal extract from the bark of the white willow tree, a natural source of salicin.',
                'manufacturer' => 'ORGANIC',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
        ];

        foreach ($apis as $api) {
            ActivePharmaceuticalIngredient::create($api);
        }
    }
}
