<?php

namespace Database\Seeders;

use App\Models\FoodProduct;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class FoodProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'AMONIUM BICARBONAT',
                'description' => 'A leavening agent commonly used in the baking industry for a crisp texture in crackers and cookies.',
                'manufacturer' => 'NCI',
                'country' => 'India',
                'packaging' => 'Bag',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'BHT',
                'description' => 'Butylated hydroxytoluene, an antioxidant used to prevent rancidity in foods containing fats and oils.',
                'manufacturer' => 'SPP',
                'country' => 'Russia',
                'packaging' => 'Bag',
                'packing_size' => '20 KG',
            ],
            [
                'name' => 'CITRIC ACID',
                'description' => 'An organic acid used as an acidity regulator, flavoring, and preservative in food and beverages.',
                'manufacturer' => 'WEIFANG',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'CITRIC ACID',
                'description' => 'High-quality citric acid for various applications in the food, beverage, and pharmaceutical industries.',
                'manufacturer' => 'RZBC',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'COLLOIDAL SILICON DIOXIDE',
                'description' => 'An anti-caking agent that ensures powdered products remain free-flowing and do not clump.',
                'manufacturer' => 'ANHUI SUNHERE',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '10 KG',
            ],
            [
                'name' => 'CONCENTRATED SOY PROTEIN',
                'description' => 'A soy protein concentrate used to increase protein content in various food products.',
                'manufacturer' => 'GUSHEN',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '20/25 KG',
            ],
            [
                'name' => 'DEXTROSEMONOHYDRATE',
                'description' => 'A readily soluble dextrose monohydrate sweetener, commonly used in beverages and baked goods.',
                'manufacturer' => 'XIWANG PHARM',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'DEXTROSEMONOHYDRATE',
                'description' => 'Dextrose monohydrate serving as a quick energy source and sweetener in the food industry.',
                'manufacturer' => 'WEIFANG',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'DICALCIUM PHOSPHATE DIHYDRATE',
                'description' => 'A calcium and phosphorus supplement used in the feed and food industries.',
                'manufacturer' => 'JIANGSU KOLOD',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'DICALCIUM PHOSPHATE ANHYDROUS',
                'description' => 'The anhydrous form of dicalcium phosphate used as a food additive.',
                'manufacturer' => 'JIANGSU KOLOD',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'FRUCTOSE 55% LIQUID SYRUP',
                'description' => 'A liquid fructose syrup with 55% sweetness, ideal for various beverage products.',
                'manufacturer' => 'JILIN COFCO BIO-CHEM',
                'country' => 'China',
                'packaging' => 'Jerrican',
                'packing_size' => '30 KG',
            ],
            [
                'name' => 'FUMARIC ACID',
                'description' => 'Fumaric acid used as an acidulant and flavor enhancer in food products.',
                'manufacturer' => 'JUSTUS SAKTI RAYA',
                'country' => 'Indonesia',
                'packaging' => 'Bag',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'GLYCERINE',
                'description' => 'Glycerine that functions as a sweetener, thickener, and preservative in the food industry.',
                'manufacturer' => 'SUMI ASIH',
                'country' => 'Indonesia',
                'packaging' => 'Drum',
                'packing_size' => '250 KG',
            ],
            [
                'name' => 'GULA RAFINASI R1',
                'description' => 'R1 quality refined sugar for industrial food and beverage needs.',
                'manufacturer' => 'JAWA MANIS',
                'country' => 'Indonesia',
                'packaging' => 'Bag',
                'packing_size' => '50 KG',
            ],
            [
                'name' => 'GLUCOSE',
                'description' => 'Glucose as a sweetener and energy source in various food products.',
                'manufacturer' => 'ROQUETE',
                'country' => 'India',
                'packaging' => 'Drum',
                'packing_size' => '50 KG',
            ],
            [
                'name' => 'GLUCOSE BRIX 85',
                'description' => 'A glucose syrup with a Brix 85 sweetness level, suitable for the candy and confectionery industry.',
                'manufacturer' => 'CARGILL',
                'country' => 'Indonesia',
                'packaging' => 'Drum',
                'packing_size' => '300 KG',
            ],
            [
                'name' => 'HYPROMELLOSE',
                'description' => 'Hydroxypropyl methylcellulose that acts as a thickener and stabilizer in food products.',
                'manufacturer' => 'ANHUI SUNHERE',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'ISOLATED SOY PROTEIN',
                'description' => 'High-purity isolated soy protein for high-protein food products.',
                'manufacturer' => 'GUSHEN',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '20 KG',
            ],
            [
                'name' => 'LHPCLH',
                'description' => 'Low-substituted hydroxypropyl cellulose for various pharmaceutical and food applications.',
                'manufacturer' => 'SHIN ETSU',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '50 KG',
            ],
            [
                'name' => 'LHPC LH-11',
                'description' => 'A specific grade of low-substituted hydroxypropyl cellulose for particular formulation needs.',
                'manufacturer' => 'ANHUI SUNHERE',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '20 KG / 25 KG',
            ],
            [
                'name' => 'MALTODEXTRINE',
                'description' => 'Maltodextrin as a filler, thickener, and bulking agent in food products.',
                'manufacturer' => 'BRITISH BUDI',
                'country' => 'Indonesia',
                'packaging' => 'Bag',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'MAGNESIUM STEARAT',
                'description' => 'Magnesium stearate that functions as an anti-adherent and lubricant.',
                'manufacturer' => 'FACI',
                'country' => 'Singapore',
                'packaging' => 'Bag',
                'packing_size' => '15 KG',
            ],
            [
                'name' => 'METHYLENE CHLORIDE',
                'description' => 'Methylene chloride solvent used in various industrial processes.',
                'manufacturer' => 'BLUE CUBE/LOTTE',
                'country' => 'USA/Korea',
                'packaging' => 'Drum',
                'packing_size' => '270KG/250KG',
            ],
            [
                'name' => 'MONOCALCIUM PHOSPHATE MONOHYDRATE',
                'description' => 'A fast-acting leavening agent, ideal for cake and biscuit doughs.',
                'manufacturer' => 'JIANGSU KOLOD',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'MODIFIED TAPIOCA STARCH E1412',
                'description' => 'Modified tapioca starch E1412 to improve texture and stability in food products.',
                'manufacturer' => 'BAO MINH TIEN',
                'country' => 'Vietnam',
                'packaging' => 'Bag',
                'packing_size' => '25KG',
            ],
            [
                'name' => 'MODIFIED TAPIOCA STARCH E1420',
                'description' => 'Modified tapioca starch E1420 that provides viscosity and clarity in sauces and soups.',
                'manufacturer' => 'BAO MINH TIEN',
                'country' => 'Vietnam',
                'packaging' => 'Bag',
                'packing_size' => '25KG',
            ],
            [
                'name' => 'MSG',
                'description' => 'Monosodium glutamate as a flavor enhancer to strengthen the umami taste in dishes.',
                'manufacturer' => 'FUFENG',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '25KG',
            ],
            [
                'name' => 'MSG',
                'description' => 'High-quality umami flavor enhancer for a wide range of culinary applications.',
                'manufacturer' => 'MEIHUA',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '25KG',
            ],
            [
                'name' => 'MSG',
                'description' => 'Monosodium glutamate produced to enhance the deliciousness of various dishes.',
                'manufacturer' => 'MIKIMOTO',
                'country' => 'Indonesia',
                'packaging' => 'Bag',
                'packing_size' => '25KG',
            ],
            [
                'name' => 'PERLITE',
                'description' => 'A filter aid material from volcanic rock for filtration processes in the beverage industry.',
                'manufacturer' => 'PERLIT',
                'country' => 'Indonesia',
                'packaging' => 'Bag',
                'packing_size' => '20 KG',
            ],
            [
                'name' => 'PEPPERMINT OIL',
                'description' => 'Peppermint oil to provide mint flavor and aroma to candies, drinks, and other products.',
                'manufacturer' => 'ANHUI YIFAN',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '50 KG',
            ],
            [
                'name' => 'POTATO STARCH',
                'description' => 'Potato starch as a natural thickener for sauces, soups, and gluten-free baked goods.',
                'manufacturer' => 'PPZ TRZEMNSNO',
                'country' => 'Poland',
                'packaging' => 'Bag',
                'packing_size' => '25KG',
            ],
            [
                'name' => 'POTATO FLAKES',
                'description' => 'Instant potato flakes for making mashed potatoes or as an ingredient in snacks.',
                'manufacturer' => 'ISCON BALAJI',
                'country' => 'India',
                'packaging' => 'Bag',
                'packing_size' => '25KG',
            ],
            [
                'name' => 'POTATO GRANULES',
                'description' => 'Potato granules for industrial food applications that require potato texture.',
                'manufacturer' => 'AVIKO RIXONA',
                'country' => 'Netherlands',
                'packaging' => 'Bag',
                'packing_size' => '25KG',
            ],
            [
                'name' => 'POTASSIUM CHLORIDE',
                'description' => 'A sodium salt substitute for low-sodium products and as a potassium supplement.',
                'manufacturer' => 'SHUREN FOOD ADDITIVE',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '25KG',
            ],
            [
                'name' => 'PROPYLENE GLYCOL',
                'description' => 'Propylene glycol as a solvent, emulsifier, and humectant in food.',
                'manufacturer' => 'DOW CHEMICAL',
                'country' => 'Thailand',
                'packaging' => 'Drum',
                'packing_size' => '215 KG',
            ],
            [
                'name' => 'PROPYLENE GLYCOL',
                'description' => 'Versatile propylene glycol for various food and pharmaceutical industry applications.',
                'manufacturer' => 'SK PIC GLOBAL',
                'country' => 'Korea',
                'packaging' => 'Drum',
                'packing_size' => '215 KG',
            ],
            [
                'name' => 'PVP K30 USP 41',
                'description' => 'Povidone K30 of USP 41 standard, used as a stabilizer and binder.',
                'manufacturer' => 'JH NANHANG',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'PVP K90 USP 41',
                'description' => 'Povidone K90 of USP 41 standard, providing stronger binding capacity.',
                'manufacturer' => 'JH NANHANG',
                'country' => 'China',
                'packaging' => 'Drum',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'SILICON DIOXIDE',
                'description' => 'Silicon dioxide as an anti-caking agent to keep powdered products free-flowing.',
                'manufacturer' => 'EVONIK',
                'country' => 'Taiwan',
                'packaging' => 'Bag',
                'packing_size' => '10 KG',
            ],
            [
                'name' => 'SODIUM STARCH GLYCOLATE',
                'description' => 'A superdisintegrant used in tablet formulations to accelerate active ingredient release.',
                'manufacturer' => 'ANHUI SUNHERE',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'SODIUM ACETATE TRIHYDRATE',
                'description' => 'Sodium acetate trihydrate as a preservative and acidity regulator.',
                'manufacturer' => 'JIANGSU KOLOD',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'SODIUM ACETATE ANHYDROUS',
                'description' => 'The anhydrous form of sodium acetate for applications requiring low water content.',
                'manufacturer' => 'JIANGSU KOLOD',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'SODIUM SACCHARIN',
                'description' => 'Sodium saccharin artificial sweetener for low-calorie products.',
                'manufacturer' => 'BATANG ALUM',
                'country' => 'Indonesia',
                'packaging' => 'Bag',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'SODIUM CICLAMATE',
                'description' => 'Sodium cyclamate artificial sweetener that provides sweetness without calories.',
                'manufacturer' => 'BATANG ALUM',
                'country' => 'Indonesia',
                'packaging' => 'Bag',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'SODIUM ACID PYROPHOSPHATE',
                'description' => 'A slow-acting leavening agent, used in refrigerated doughs.',
                'manufacturer' => 'JIANGSU KOLOD',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'SOYBEAN DIETARY FIBER',
                'description' => 'Dietary fiber from soybeans to increase the fiber content in food products.',
                'manufacturer' => 'GUSHEN',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '15/20 KG',
            ],
            [
                'name' => 'SOY MILK POWDER',
                'description' => 'Soy milk powder as a plant-based, protein-rich alternative to animal milk.',
                'manufacturer' => 'GUSHEN',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '20 KG',
            ],
            [
                'name' => 'SOY LECITHIN',
                'description' => 'Soy lecithin as a natural emulsifier to blend oil and water-based ingredients.',
                'manufacturer' => 'GUSHEN',
                'country' => 'China',
                'packaging' => 'Vat/Drum',
                'packing_size' => '25/200 KG',
            ],
            [
                'name' => 'SOY POLYSACCHARIDE',
                'description' => 'Soy polysaccharide that functions as a stabilizer and emulsifier in protein beverages.',
                'manufacturer' => 'GUSHEN',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '20 KG',
            ],
            [
                'name' => 'SWEET POTATO STARCH',
                'description' => 'Sweet potato starch that provides a chewy and soft texture, ideal for noodles and cakes.',
                'manufacturer' => 'BAO MINH TIEN',
                'country' => 'Vietnam',
                'packaging' => 'Bag',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'TRICALCIUM PHOSPHATE',
                'description' => 'Tricalcium phosphate as an anti-caking agent and additional calcium source.',
                'manufacturer' => 'JIANGSU KOLOD',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '25 KG',
            ],
            [
                'name' => 'TEXTURED SOY PROTEIN CONCENTRATE',
                'description' => 'Textured soy protein concentrate as a plant-based meat substitute.',
                'manufacturer' => 'GUSHEN',
                'country' => 'China',
                'packaging' => 'Bag',
                'packing_size' => '20 KG',
            ],
            [
                'name' => 'VASELINALBUM',
                'description' => 'Vaselinum album (white petrolatum) for various pharmaceutical and cosmetic applications.',
                'manufacturer' => 'SASOL',
                'country' => 'Germany',
                'packaging' => 'Drum',
                'packing_size' => '195 KG',
            ],
        ];

        foreach ($products as $product) {
            FoodProduct::create($product);
        }
    }
}
